### PR TITLE
Enhance the build process

### PR DESCRIPTION
**Pull request by crisbal**
As discussed in #3 

Things to note:

* Add a build process with Webpack (during development the page will reload itself when any change to the CSS/JS occours)
* The deploy process to the `gh-pages` branch should be handled by [git-directory-deploy](https://github.com/X1011/git-directory-deploy), I added instructions in the readme, basically `npm run build` and `./deploy.sh` (you will need to download `./deploy.sh` from the linked repo.

As of right now the project should be the same as it was before, just a little bit cleaner in terms of code structure. 

Let me know if something is not clear

### CODE REVIEW

**Comment by crisbal** [comment]
I decided not to use Travis for deployment since this solution is easier. The only downside with this kind of deployment is it has to be done "manually" (You need to remember to run the script when you want to deploy a new version)

**Comment by crisbal** [comment]
I also tweaked a bit the sidebar/drawer so it does look a bit more consistent, let me know if you like it

deepin-screenshot syjwqm

**Comment by crisbal** [comment]
Hey @lays147 did you have a chance to check the PR?

**Comment by lays147** [comment]
@crisbal sorry. My life was crazy this past day, after Christmas Holidays I will look, ok? 
Merry XMas!

**Comment by crisbal** [comment]
Hey Lays, no problem, take your time! I am also having some busy days lately. Just wanted to check if you got the notification. Happy Christmas!

**Pull request merged**
